{{- if .Values.terraformToken -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tfc_plan_notifier.fullname" . }}
  labels:
    {{- include "tfc_plan_notifier.labels" . | nindent 4 }}
data:
  TERRAFORM_TOKEN: "{{ .Values.terraformToken }}"
{{- end }}
